name = "debianclub"
compatibility_date = "2024-06-07"
pages_build_output_dir = "web/out"

[build]
command = "corepack enable && pnpm --dir web install --frozen-lockfile && pnpm --dir web build"
cwd = "."
watch_dir = "web"
