import type { ToolLanguage } from './types';

export const toolText = {
  zh: {
    title: 'Debian 交互工具',
    subtitle: '本地运行的选择器和向导。不会上传数据，也不会自动修改系统。',
    badge: '本地运行',
    copy: '复制',
    copied: '已复制',
    recommended: '推荐',
    why: '原因',
    next: '下一步',
    notes: '注意事项',
    output: '输出',
    commands: '只读检查',
    reviewBeforeUse: '应用前先核对发行版代号、镜像站、组件和当前系统状态。',
    tabs: {
      mirror: '镜像源',
      install: '安装方式',
      desktop: '桌面环境',
      partition: '分区方案',
      troubleshoot: '排障向导',
      safety: '命令安全',
      skills: 'AI Skills',
      upgrade: '升级规划',
    },
    mirror: {
      title: '镜像源选择器',
      release: '发行版',
      mirror: '镜像站',
      components: '组件范围',
      snippet: 'deb822 sources 建议',
      command: '编辑命令',
      docs: '查看 deb822 源格式',
      share: '复制镜像配置链接',
      shareCopied: '配置链接已复制',
    },
    install: {
      title: '安装方式选择器',
      device: '设备',
      goal: '目标',
      risk: '风险偏好',
      docs: '查看安装指南',
      share: '复制安装配置链接',
      shareCopied: '配置链接已复制',
    },
    desktop: {
      title: '桌面环境选择器',
      hardware: '硬件性能',
      workflow: '工作流',
      docs: '查看桌面环境',
      share: '复制桌面配置链接',
      shareCopied: '配置链接已复制',
    },
    partition: {
      title: '分区方案生成器',
      disk: '磁盘',
      boot: '启动模式',
      encryption: '加密',
      docs: '查看磁盘管理',
      share: '复制分区配置链接',
      shareCopied: '配置链接已复制',
    },
    troubleshoot: {
      title: '排障问诊向导',
      symptom: '问题现象',
      docs: '查看排障文档',
      share: '复制排障配置链接',
      shareCopied: '配置链接已复制',
    },
    safety: {
      title: '命令安全检查器',
      input: '粘贴要检查的命令',
      placeholder: '每行一个命令。示例：sudo apt update',
      summarySafe: '未命中已知高风险模式',
      summaryReview: '需要人工复核',
      summaryWarning: '发现高风险命令',
      summaryCritical: '发现应阻止的危险命令',
      noFindings:
        '没有发现远程脚本管道执行、递归强删、危险磁盘写入或 SSH 安全降级等模式。仍需确认命令来源、路径和当前机器状态。',
      docs: '查看 AI Skills 安全边界',
      critical: '阻止',
      warning: '高风险',
      review: '复核',
      safer: '更安全做法',
      share: '复制分享链接',
      shareCopied: '链接已复制',
    },
    skills: {
      title: 'AI Skills 安装命令生成器',
      target: '安装位置',
      replace: '替换已有安装',
      install: '安装命令',
      validate: '验证命令',
      docs: '查看 AI Skills 文档',
      targetNote: '命令需要在 DebianClub 仓库根目录执行。',
      share: '复制 Skills 配置链接',
      shareCopied: '配置链接已复制',
    },
    upgrade: {
      title: '升级规划器',
      current: '当前版本',
      target: '目标',
      exposure: '暴露面',
      share: '复制升级规划链接',
      shareCopied: '规划链接已复制',
      docs: '查看升级指南',
      checks: '升级前检查',
      schedule: '建议窗口',
    },
  },
  en: {
    title: 'Debian Interactive Tools',
    subtitle: 'Local selectors and wizards. No data upload and no automatic system changes.',
    badge: 'Local tools',
    copy: 'Copy',
    copied: 'Copied',
    recommended: 'Recommended',
    why: 'Why',
    next: 'Next step',
    notes: 'Notes',
    output: 'Output',
    commands: 'Read-only checks',
    reviewBeforeUse: 'Before applying, verify the release codename, mirror, components, and current system state.',
    tabs: {
      mirror: 'Mirrors',
      install: 'Install',
      desktop: 'Desktop',
      partition: 'Partitions',
      troubleshoot: 'Troubleshoot',
      safety: 'Command Safety',
      skills: 'AI Skills',
      upgrade: 'Upgrade',
    },
    mirror: {
      title: 'Mirror Selector',
      release: 'Release',
      mirror: 'Mirror',
      components: 'Components',
      snippet: 'Suggested deb822 sources',
      command: 'Edit command',
      docs: 'Read deb822 sources guide',
      share: 'Copy mirror config link',
      shareCopied: 'Config link copied',
    },
    install: {
      title: 'Install Planner',
      device: 'Device',
      goal: 'Goal',
      risk: 'Risk preference',
      docs: 'Read installation guide',
      share: 'Copy install config link',
      shareCopied: 'Config link copied',
    },
    desktop: {
      title: 'Desktop Picker',
      hardware: 'Hardware',
      workflow: 'Workflow',
      docs: 'Read desktop guide',
      share: 'Copy desktop config link',
      shareCopied: 'Config link copied',
    },
    partition: {
      title: 'Partition Planner',
      disk: 'Disk',
      boot: 'Boot mode',
      encryption: 'Encryption',
      docs: 'Read disk management',
      share: 'Copy partition config link',
      shareCopied: 'Config link copied',
    },
    troubleshoot: {
      title: 'Troubleshooting Wizard',
      symptom: 'Symptom',
      docs: 'Read troubleshooting docs',
      share: 'Copy troubleshooting link',
      shareCopied: 'Config link copied',
    },
    safety: {
      title: 'Command Safety Checker',
      input: 'Paste commands to check',
      placeholder: 'One command per line. Example: sudo apt update',
      summarySafe: 'No known high-risk pattern found',
      summaryReview: 'Manual review needed',
      summaryWarning: 'High-risk command found',
      summaryCritical: 'Dangerous command should be blocked',
      noFindings:
        'No remote script piping, recursive force deletion, destructive disk writes, or SSH security downgrades were detected. Still verify command source, paths, and the current machine state.',
      docs: 'Read AI Skills safety boundaries',
      critical: 'Block',
      warning: 'High risk',
      review: 'Review',
      safer: 'Safer approach',
      share: 'Copy share link',
      shareCopied: 'Link copied',
    },
    skills: {
      title: 'AI Skills Installer',
      target: 'Install target',
      replace: 'Replace existing install',
      install: 'Install command',
      validate: 'Validation command',
      docs: 'Read AI Skills docs',
      targetNote: 'Run the command from the DebianClub repository root.',
      share: 'Copy Skills config link',
      shareCopied: 'Config link copied',
    },
    upgrade: {
      title: 'Upgrade Planner',
      current: 'Current release',
      target: 'Target',
      exposure: 'Exposure',
      share: 'Copy upgrade plan link',
      shareCopied: 'Plan link copied',
      docs: 'Read upgrade guide',
      checks: 'Pre-upgrade checks',
      schedule: 'Suggested window',
    },
  },
} as const satisfies Record<ToolLanguage, unknown>;

export const docsHref = {
  zh: {
    deb822: '/administration/deb822',
    install: '/basics/installation',
    desktop: '/basics/desktop-environments',
    disk: '/administration/disk-management',
    troubleshoot: '/troubleshooting/faq',
    safety: '/ai/skills/safety',
    skills: '/ai/skills/install',
    upgrade: '/basics/upgrade',
  },
  en: {
    deb822: '/en/administration/deb822',
    install: '/en/basics/installation',
    desktop: '/en/basics/desktop-environments',
    disk: '/en/administration/disk-management',
    troubleshoot: '/en/troubleshooting/faq',
    safety: '/en/ai/skills/safety',
    skills: '/en/ai/skills/install',
    upgrade: '/en/basics/upgrade',
  },
} as const;
